spring:
  datasource:
    url: ${DB_HOMOLOG_URL}
    username: ${DB_HOMOLOG_USERNAME}
    password: ${DB_HOMOLOG_PASSWORD}
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: create
