spring:
  datasource:
    url: jdbc:mariadb://${DB_MARIA_SERVER:localhost}:${DB_MARIA_PORT:3306}/${DB_MARIA_NAME:cp3-seguradora}?createDatabaseIfNotExist=true
    username: ${DB_MARIA_USERNAME:root}
    password: ${DB_MARIA_PASSWORD:root}
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: create